### ISSUE TITLE
Adjust Speed Based on Width

### ISSUE THREAD

**Issue by graygilmore** [pixelunion/jOverscroll#1]
Short lines require quicker speeds, longer lines require longer speeds. Would be great to somehow put together an option for `scrollTime` that calculates the 'comfortable reading speed' of that line.

**Comment by jarednorman** [comment]
OH YOU JUST WANT EVERYTHING

**Comment by jarednorman** [comment]
Nah I'm kidding, sure I'll add that.

**Comment by jarednorman** [comment]
Actually, no I won't.
